const ACTIONS = {
  ADD_BASKET: 'ADD_BASKET',
  REMOVE_BASKET: 'REMOVE_BASKET',
  SEARCH_TEXT: 'SEARCH_TEXT',
  FILTER: 'FILTER',
  ORDER: 'ORDER',
  CLEAR_FILTERS: 'CLEAR_FILTERS',
};

const ORDERS = {
  DESC_PRICE: 'DESC_PRICE',
  ASC_PRICE: 'ASC_PRICE',
  DESC_CREATED_AT: 'DESC_CREATED_AT',
  ASC_CREATED_AT: 'ASC_CREATED_AT',
};

export { ACTIONS, ORDERS };
